<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

class CreateCampaignTest extends TestCase
{
    /**
     * A basic unit test example.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }
    public function testStore()
    {

    }

    public function testShow(){

    }

    public function testUpdate(){

    }

    public function testDestroy(){

    }
    public function test_example(): void
    {
        $this->assertTrue(true);
    }
}
